### ISSUE TITLE
which version of k8s should be used?

### ISSUE THREAD

**Issue by sheepcat** [tinkerbell/k8s-sandbox#14]
hi  guys 

i  try to deploy tinkerbell in k8s  v1.22.3 
but it raise :

no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"

[root@k8s-master kubernetes]# kk api-resources  |grep admissionregistration
mutatingwebhookconfigurations                  admissionregistration.k8s.io/v1        false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io/v1        false        ValidatingWebhookConfiguration

what version should i used?   thanks .

**Comment by tstromberg** [comment]
Relating to #13 - though I believe that Kubernetes v1.21 should work.

**Comment by tstromberg** [comment]
The general answer is: we support the latest stable release of Kubernetes. It so happens that due to #13 that we recommend v1.21.x today.
